export const SET_OPEN_FORM_REGISTER = "SET_OPEN_FORM_REGISTER";
export const SET_OPEN_FORM_REGISTER_REQUEST = "SET_OPEN_FORM_REGISTER_REQUEST";
export const SET_CLOSE_FORM_REGISTER_REQUEST =
  "SET_CLOSE_FORM_REGISTER_REQUEST";
export const SET_OPEN_FORM_REGISTER_EFFECT = "SET_OPEN_FORM_REGISTER_EFFECT";
