export const SET_OPEN_FORM_REGISTER = "SET_OPEN_FORM_REGISTER";
export const SET_OPEN_FORM_REGISTER_REQUEST = "SET_OPEN_FORM_REGISTER_REQUEST";
export const SET_CLOSE_FORM_REGISTER_REQUEST =
  "SET_CLOSE_FORM_REGISTER_REQUEST";
export const SET_OPEN_FORM_REGISTER_EFFECT = "SET_OPEN_FORM_REGISTER_EFFECT";
export const SUBMIT_FORM_REGISTER = "SUBMIT_FORM_REGISTER";
export const CLEAR_REGISTER_FORM = "CLEAR_REGISTER_FORM";
export const SET_REGISTER_FORM_DATA = "SET_REGISTER_FORM_DATA";
export const SET_NOTIFY = "SET_NOTIFY";
export const SEARCH_CEP = "SEARCH_CEP";
export const LOAD_DATA_GRID_REQUEST = "LOAD_DATA_GRID_REQUEST";
export const SET_DATA_GRID = "SET_DATA_GRID";
export const SET_DATA_GRID_LOADING = "SET_DATA_GRID_LOADING";
export const SET_DATA_GRID_START = "SET_DATA_GRID_START";
export const SET_DATA_GRID_SIZE = "SET_DATA_GRID_SIZE";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const SET_FORM_REGISTER_CLIENT_ID = "SET_FORM_REGISTER_CLIENT_ID";
export const SET_SEARCH_CLIENT_NAME_DATA_GRID =
  "SET_SEARCH_CLIENT_NAME_DATA_GRID";
export const SUBMIT_SEARCH_CLIENT_FORM = "SUBMIT_SEARCH_CLIENT_FORM";
export const SET_SEARCH_CLIENT_AUTOCOMPLETE = "SET_SEARCH_CLIENT_AUTOCOMPLETE";
export const SET_OPEN_FORM_MEDICAL_HISTORY = "SET_OPEN_FORM_MEDICAL_HISTORY";
export const SET_OPEN_FORM_MEDICAL_HISTORY_REQUEST =
  "SET_OPEN_FORM_MEDICAL_HISTORY_REQUEST";
export const SET_CLOSE_FORM_MEDICAL_HISTORY_REQUEST =
  "SET_CLOSE_FORM_MEDICAL_HISTORY_REQUEST";
export const SET_OPEN_FORM_MEDICAL_HISTORY_EFFECT =
  "SET_OPEN_FORM_MEDICAL_HISTORY_EFFECT";
export const SET_FORM_MEDICAL_HISTORY_DATA = "SET_FORM_MEDICAL_HISTORY_DATA";
export const SET_CONFIRM_MODAL = "SET_CONFIRM_MODAL";
export const SUBMIT_MEDICAL_HISTORY_FORM = "SUBMIT_MEDICAL_HISTORY_FORM";
