export const SET_OPEN_FORM_REGISTER = "SET_OPEN_FORM_REGISTER";
export const SET_OPEN_FORM_REGISTER_REQUEST = "SET_OPEN_FORM_REGISTER_REQUEST";
export const SET_CLOSE_FORM_REGISTER_REQUEST =
  "SET_CLOSE_FORM_REGISTER_REQUEST";
export const SET_OPEN_FORM_REGISTER_EFFECT = "SET_OPEN_FORM_REGISTER_EFFECT";
export const SUBMIT_FORM_REGISTER = "SUBMIT_FORM_REGISTER";
export const CLEAR_REGISTER_FORM = "CLEAR_REGISTER_FORM";
export const SET_REGISTER_FORM_DATA = "SET_REGISTER_FORM_DATA";
export const SET_NOTIFY = "SET_NOTIFY";
export const SEARCH_CEP = "SEARCH_CEP";
