POST https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente HTTP/1.1
content-type: text/xml;charset=UTF-8

<?xml version="1.0"?>
    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">
      <soapenv:Header />
        <soapenv:Body>
            <cli:consultaCEP>
                  <cep>00000000</cep>
            </cli:consultaCEP>
        </soapenv:Body>
    </soapenv:Envelope>